### PR TITLE
Added dark mode in home.html 

### PR DESCRIPTION
**Pull request by oneofthedevs**
Added dark mode feature and toggle btn for index.html

If you like the changes can you please first accept the pull request then I can start working for rest of the pages

### CODE REVIEW

**Comment by hariomkushwaha** [comment]
@oneofthedevs send the ss of your change

**Comment by oneofthedevs** [comment]
d3
d1
d2

**Comment by hariomkushwaha** [comment]
@oneofthedevs nice

**Comment by hariomkushwaha** [comment]
@oneofthedevs make for all the pages

**Comment by oneofthedevs** [comment]
Sure, is it okay If I do it on weekends?

**Pull request merged**
