### PR TITLE
Feature added (popup for login and register)

### PR DESCRIPTION
**Pull request by BhupaliRane**
Popup for login and register added. Please merge it.
Thank You.

### CODE REVIEW

**Comment by hariomkushwaha** [comment]
@BhupaliRane may you show me what you have changed. send the pic of that

**Comment by BhupaliRane** [comment]
**1. Added 2 buttons for login and register**

Screenshot (583)

**2. After clicking login button, Login form will be popup**

Screenshot (580)

**3. After clicking register button, Register form will be popup**

Screenshot (581)

**Comment by BhupaliRane** [comment]
Hope this will be useful. If any changes want to be done please let me know.

**Comment by BhupaliRane** [comment]
Thank you

**Pull request merged**
